### ISSUE TITLE
SQLx now supports MSSQL.

### ISSUE THREAD

**Issue by maxnachlinger** [prisma/quaint#220]
If you'd like to pull more of the connector responsibility out of quaint, SQLx's MSSQL support might be a way to do that. I know this is an odd call-out since you guys maintain tiberius :) Perhaps the SQLx devs could leverage the awesome work that's gone in to tiberius.

**Comment by maxnachlinger** [comment]
Closed since this isn't really an issue per se

**Comment by codebling** [comment]
SQLx's mssql support currently seems immature -- it doesn't support Numeric or Datetime types (even with those crate features enabled). You can see this by comparing [`sqlx-core/src/postgres/types`](https://github.com/launchbadge/sqlx/tree/main/sqlx-core/src/postgres/types) with [`sqlx-core/src/mssql/types`](https://github.com/launchbadge/sqlx/tree/main/sqlx-core/src/mssql/types). It also fails if a column size is set to MAX.
