### ISSUE TITLE
Old version of SQLite connector

### ISSUE THREAD

**Issue by sartor** [prisma/quaint#236]
library now have old dependency in rusqlite (version 0.17) but fresh version is 0.24. I need to use UPSERT sql construction, but it became available only since rusqlite v0.20.0 (https://github.com/rusqlite/rusqlite/releases)

Is there any reasons to use so old version of rusqlite and libsqlite3-sys ?

**Comment by pimeys** [comment]
Probably the reason is that we have seven million dependencies in Prisma and we can't track all of them always. Also we haven't needed new version of sqlite yet, so we haven't updated it.

I'm happy to review a pull request always!
