### ISSUE TITLE
Should we have a changelog?

### ISSUE THREAD

**Issue by tomhoule** [prisma/quaint#55]

**Comment by pimeys** [comment]
Yes.

**Comment by pimeys** [comment]
What I've now done is I just tag the version released to crates.io. Gathering a changelog from that would be easy.

**Comment by janpio** [comment]
(Maybe https://github.com/conventional-changelog/conventional-changelog)

**Comment by pimeys** [comment]
https://github.com/prisma/quaint/blob/master/CHANGELOG.md
