### ISSUE TITLE
MySQL Error: column() vs. columns()

### ISSUE THREAD

**Issue by joebubna** [prisma/quaint#56]
Hi guys,

First, thanks for releasing this project. The flexibility it provides is exactly what I was looking for and I appreciate you opening it up to the community. 

That said, I was trying to use the package and having a heck of a time (I almost gave up on it) because I kept running into an error, even when I was practically copy-pasting examples from the documentation. After further digging I've narrowed the issue down to the columns() method in the query builder which doesn't seem to play nice with MySQL 5.6 which I was testing on. I don't know if the same issue persists on all versions of MySQL, but I figured I'd inform you guys. (Or maybe I'm doing something wrong and need to be educated?).

In the code below I attempt to run the same query and get the results, first using multiple column() calls, and the second with a single columns() call. Here's the code, then I'll post the results I get after:

### CODE

```rust
#[derive(Debug, PartialEq, Eq)]
pub struct User {
  pub user_id: Option<i64>,
  pub first_name: Option<String>,
  pub last_name: Option<String>,
}

// Setup
let pool = Quaint::new("mysql://root:root@127.0.0.1:3306/some_database").await?;
let conn = pool.check_out().await?;

// ///////////////////////////////////////////////////////////
// First query with each column specified individually - WORKS
// ///////////////////////////////////////////////////////////
println!("\r\n\r\n#################  FIRST QUERY  #################\r\n");

// Build query
let query1 = Select::from_table("users")
  .column("user_id")
  .column("first_name") 
  .column("last_name")
  .limit(5);

// Output the SQL generated
let (sql_str1, params) = Mysql::build(query1.clone());
println!("{}", sql_str1);

// Run the query and print the number of returned results
let results = conn.query(Query::from(query1)).await.unwrap();
println!("Number of results: {}", results.len());

// Try grabbing and printing the first result
if let Some(row) = results.get(0) {
  println!("{:#?}", row);

  let user = User {
    user_id: row["user_id"].as_i64(),
    first_name: row["first_name"].to_string(),
    last_name: row["last_name"].to_string(),
  };
  println!("{:#?}", user);
};


// ///////////////////////////////////////////////////////////
// Second query with columns specified in array - BROKEN
// ///////////////////////////////////////////////////////////
println!("\r\n\r\n#################  SECOND QUERY  #################\r\n");

// Build query
let query2 = Select::from_table("users")
  .columns(vec!["user_id", "first_name", "last_name"])
  .limit(5);

// Output the SQL generated
let (sql_str2, params) = Mysql::build(query2.clone());
println!("{}", sql_str2);

// Run the query and print the number of returned results
let results = conn.query(Query::from(query2)).await.unwrap();
println!("Number of results: {}", results.len());

// Try grabbing and printing the first result
if let Some(row) = results.get(0) {
  println!("{:#?}", row);

  let user = User {
    user_id: row["user_id"].as_i64(),
    first_name: row["first_name"].to_string(),
    last_name: row["last_name"].to_string(),
  };
  println!("{:#?}", user);
};
```

### RESULTS:

```
#################  FIRST QUERY  #################

SELECT `user_id`, `first_name`, `last_name` FROM `users` LIMIT ?
Number of results: 5
ResultRowRef {
    name_to_index: {
        "first_name": 1,
        "last_name": 2,
        "user_id": 0,
    },
    values: [
        Integer(
            1,
        ),
        Text(
            "John",
        ),
        Text(
            "Doe",
        ),
    ],
}
User {
    user_id: Some(
        1,
    ),
    first_name: Some(
        "John",
    ),
    last_name: Some(
        "Doe",
    ),
}


#################  SECOND QUERY  #################

SELECT ?, ?, ? FROM `users` LIMIT ?
Number of results: 5
ResultRowRef {
    name_to_index: {
        "?": 2,
    },
    values: [
        Text(
            "user_id",
        ),
        Text(
            "first_name",
        ),
        Text(
            "last_name",
        ),
    ],
}
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
```

### Things to note

Notice that in both cases the number of rows returned is correct at 5, however the results are messed up in the second scenario as they are just the column names and the program obviously panics when trying to unwrap.

------------------------------------
SNIP (I think this was wrong, see my next comment)

> The documentation on prepared queries for MySQL 5.6 seem to indicate that placeholders for column names should work (https://dev.mysql.com/doc/refman/5.6/en/sql-prepared-statements.html) 

------------------------------------

So I'm not positive where the error is coming from, but it's obviously by the difference in the generated query between column() and columns(), so for the moment I'm just going to avoid columns().

Hope I explained that well. I realize the error could be in the version of MySQL I tested on, or the Rust MySQL library, but I figured I'd submit a report and let you take a look at it. Cheers guys, thanks again and sorry about throwing a bug report your way!

**Comment by joebubna** [comment]
I took a closer look at the MySQL documentation as well as did some searching. If you search for info about prepared statements and MySQL the consensus from people that know what they are talking about seems to be that you can't use passed in values as identifiers within the query.

A closer look at the documentation on prepared queries seem to confirm this:

```sql
mysql> SET @s = 'SELECT SQRT(POW(?,2) + POW(?,2)) AS hypotenuse';
mysql> PREPARE stmt2 FROM @s;
mysql> SET @a = 6;
mysql> SET @b = 8;
mysql> EXECUTE stmt2 USING @a, @b;
```

In this example from the official docs, although we are using placeholders in the projection part of the query, the placeholders are still values, and thus valid.

```sql
mysql> USE test;
mysql> CREATE TABLE t1 (a INT NOT NULL);
mysql> INSERT INTO t1 VALUES (4), (8), (11), (32), (80);

mysql> SET @table = 't1';
mysql> SET @s = CONCAT('SELECT * FROM ', @table);

mysql> PREPARE stmt3 FROM @s;
mysql> EXECUTE stmt3;
```

In this example from the docs, notice the placeholder value is concatenated to the query string before the statement is prepared - because table names are identifiers and not values, so cannot be passed in to prepare.

The query that is generated when using the columns() method outputs:

```sql
SELECT ?, ?, ? FROM `users` LIMIT ?
``` 

After this further review, I believe the error is in that generated statement because placeholders for column names don't seem to be valid in MySQL.

**Comment by pimeys** [comment]
Ha! Good catch. It should be an easy fix, and it seems we don't use `columns` in our code that much. I'll come back to this later when I can reproduce it.

**Comment by pimeys** [comment]
Nice to have some new users to see things we don't use or test. This was an easy fix, but could you @joebubna try the latest master and see if it works in both use cases?

**Comment by pimeys** [comment]
I'll release a new version to crates.io if it works out for you.

**Comment by pimeys** [comment]
I also created a discord chat for quaint. Happy to help and hear how people are using quaint in their projects. https://discord.gg/r4CPY4B

**Comment by joebubna** [comment]
That fixed it. Thanks for the fast response!

Marking this as closed.
